package Modele;
// Generated 2018-09-08 03:12:36 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Bail generated by hbm2java
 */
public class Bail  implements java.io.Serializable {


     private BailId id;
     private Locataire locataire;
     private Date dateFin;
     private Integer bienid;

    public Bail() {
    }

	
    public Bail(BailId id, Locataire locataire) {
        this.id = id;
        this.locataire = locataire;
    }
    public Bail(BailId id, Locataire locataire, Date dateFin, Integer bienid) {
       this.id = id;
       this.locataire = locataire;
       this.dateFin = dateFin;
       this.bienid = bienid;
    }
   
    public BailId getId() {
        return this.id;
    }
    
    public void setId(BailId id) {
        this.id = id;
    }
    public Locataire getLocataire() {
        return this.locataire;
    }
    
    public void setLocataire(Locataire locataire) {
        this.locataire = locataire;
    }
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }
    public Integer getBienid() {
        return this.bienid;
    }
    
    public void setBienid(Integer bienid) {
        this.bienid = bienid;
    }




}


