package Modele;
// Generated 2018-09-08 03:12:36 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BailId generated by hbm2java
 */
public class BailId  implements java.io.Serializable {


     private String immeubleid;
     private int locataireid;
     private Date dateDebut;

    public BailId() {
    }

    public BailId(String immeubleid, int locataireid, Date dateDebut) {
       this.immeubleid = immeubleid;
       this.locataireid = locataireid;
       this.dateDebut = dateDebut;
    }
   
    public String getImmeubleid() {
        return this.immeubleid;
    }
    
    public void setImmeubleid(String immeubleid) {
        this.immeubleid = immeubleid;
    }
    public int getLocataireid() {
        return this.locataireid;
    }
    
    public void setLocataireid(int locataireid) {
        this.locataireid = locataireid;
    }
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BailId) ) return false;
		 BailId castOther = ( BailId ) other; 
         
		 return ( (this.getImmeubleid()==castOther.getImmeubleid()) || ( this.getImmeubleid()!=null && castOther.getImmeubleid()!=null && this.getImmeubleid().equals(castOther.getImmeubleid()) ) )
 && (this.getLocataireid()==castOther.getLocataireid())
 && ( (this.getDateDebut()==castOther.getDateDebut()) || ( this.getDateDebut()!=null && castOther.getDateDebut()!=null && this.getDateDebut().equals(castOther.getDateDebut()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getImmeubleid() == null ? 0 : this.getImmeubleid().hashCode() );
         result = 37 * result + this.getLocataireid();
         result = 37 * result + ( getDateDebut() == null ? 0 : this.getDateDebut().hashCode() );
         return result;
   }   


}


