package Modele;
// Generated 2018-09-08 03:12:36 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Bienimmobilier generated by hbm2java
 */
public class Bienimmobilier  implements java.io.Serializable {


     private BienimmobilierId id;
     private Immeuble immeuble;
     private String typeBienimmobilier;
     private BigDecimal prixLoyer;

    public Bienimmobilier() {
    }

	
    public Bienimmobilier(BienimmobilierId id, Immeuble immeuble) {
        this.id = id;
        this.immeuble = immeuble;
    }
    public Bienimmobilier(BienimmobilierId id, Immeuble immeuble, String typeBienimmobilier, BigDecimal prixLoyer) {
       this.id = id;
       this.immeuble = immeuble;
       this.typeBienimmobilier = typeBienimmobilier;
       this.prixLoyer = prixLoyer;
    }
   
    public BienimmobilierId getId() {
        return this.id;
    }
    
    public void setId(BienimmobilierId id) {
        this.id = id;
    }
    public Immeuble getImmeuble() {
        return this.immeuble;
    }
    
    public void setImmeuble(Immeuble immeuble) {
        this.immeuble = immeuble;
    }
    public String getTypeBienimmobilier() {
        return this.typeBienimmobilier;
    }
    
    public void setTypeBienimmobilier(String typeBienimmobilier) {
        this.typeBienimmobilier = typeBienimmobilier;
    }
    public BigDecimal getPrixLoyer() {
        return this.prixLoyer;
    }
    
    public void setPrixLoyer(BigDecimal prixLoyer) {
        this.prixLoyer = prixLoyer;
    }




}


