package Modele;
// Generated 2018-09-14 01:24:50 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Bienimmobilier generated by hbm2java
 */
public class Bienimmobilier  implements java.io.Serializable {


     private BienimmobilierId id;
     private Immeuble immeuble;
     private String typeBienimmobilier;
     private BigDecimal prixLoyer;
     private Set annonces = new HashSet(0);
     private Set visites = new HashSet(0);
     private Set images = new HashSet(0);
     private Set bails = new HashSet(0);

    public Bienimmobilier() {
    }

	
    public Bienimmobilier(BienimmobilierId id, Immeuble immeuble) {
        this.id = id;
        this.immeuble = immeuble;
    }
    public Bienimmobilier(BienimmobilierId id, Immeuble immeuble, String typeBienimmobilier, BigDecimal prixLoyer, Set annonces, Set visites, Set images, Set bails) {
       this.id = id;
       this.immeuble = immeuble;
       this.typeBienimmobilier = typeBienimmobilier;
       this.prixLoyer = prixLoyer;
       this.annonces = annonces;
       this.visites = visites;
       this.images = images;
       this.bails = bails;
    }
      public Bienimmobilier(BienimmobilierId id, Immeuble immeuble, String typeBienimmobilier, BigDecimal prixLoyer) {
       this.id = id;
       this.immeuble = immeuble;
       this.typeBienimmobilier = typeBienimmobilier;
       this.prixLoyer = prixLoyer;
    }
   
    public BienimmobilierId getId() {
        return this.id;
    }
    
    public void setId(BienimmobilierId id) {
        this.id = id;
    }
    public Immeuble getImmeuble() {
        return this.immeuble;
    }
    
    public void setImmeuble(Immeuble immeuble) {
        this.immeuble = immeuble;
    }
    public String getTypeBienimmobilier() {
        return this.typeBienimmobilier;
    }
    
    public void setTypeBienimmobilier(String typeBienimmobilier) {
        this.typeBienimmobilier = typeBienimmobilier;
    }
    public BigDecimal getPrixLoyer() {
        return this.prixLoyer;
    }
    
    public void setPrixLoyer(BigDecimal prixLoyer) {
        this.prixLoyer = prixLoyer;
    }
    public Set getAnnonces() {
        return this.annonces;
    }
    
    public void setAnnonces(Set annonces) {
        this.annonces = annonces;
    }
    public Set getVisites() {
        return this.visites;
    }
    
    public void setVisites(Set visites) {
        this.visites = visites;
    }
    public Set getImages() {
        return this.images;
    }
    
    public void setImages(Set images) {
        this.images = images;
    }
    public Set getBails() {
        return this.bails;
    }
    
    public void setBails(Set bails) {
        this.bails = bails;
    }




}


