package Modele;
import com.google.gson.annotations.SerializedName;
// Generated 2018-09-14 01:24:50 by Hibernate Tools 4.3.1



/**
 * BienimmobilierId generated by hbm2java
 */
public class BienimmobilierId  implements java.io.Serializable {


     private int bienid;
     private String immeubleid;

    public BienimmobilierId() {
    }

    public BienimmobilierId(int bienid, String immeubleid) {
       this.bienid = bienid;
       this.immeubleid = immeubleid;
    }
   
    public int getBienid() {
        return this.bienid;
    }
    
    public void setBienid(int bienid) {
        this.bienid = bienid;
    }
    public String getImmeubleid() {
        return this.immeubleid;
    }
    
    public void setImmeubleid(String immeubleid) {
        this.immeubleid = immeubleid;
    }
    public String toString (){
        return "BienimmobilierId [bienid=" +this.bienid+", immeubleid=" +this.immeubleid+"]";
    }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BienimmobilierId) ) return false;
		 BienimmobilierId castOther = ( BienimmobilierId ) other; 
         
		 return (this.getBienid()==castOther.getBienid())
 && ( (this.getImmeubleid()==castOther.getImmeubleid()) || ( this.getImmeubleid()!=null && castOther.getImmeubleid()!=null && this.getImmeubleid().equals(castOther.getImmeubleid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getBienid();
         result = 37 * result + ( getImmeubleid() == null ? 0 : this.getImmeubleid().hashCode() );
         return result;
   }   


}


