package Modele;
// Generated 2018-09-14 01:24:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private String clientid;
     private String nom;
     private String prenom;
     private String telephone;
     private String courriel;
     private Set utilisateurs = new HashSet(0);
     private Set visites = new HashSet(0);

    public Client() {
    }

	
    public Client(String clientid, String nom) {
        this.clientid = clientid;
        this.nom = nom;
    }
    public Client(String clientid, String nom, String prenom, String telephone, String courriel, Set utilisateurs, Set visites) {
       this.clientid = clientid;
       this.nom = nom;
       this.prenom = prenom;
       this.telephone = telephone;
       this.courriel = courriel;
       this.utilisateurs = utilisateurs;
       this.visites = visites;
    }
     public Client(String clientid, String nom, String prenom, String telephone, String courriel) {
       this.clientid = clientid;
       this.nom = nom;
       this.prenom = prenom;
       this.telephone = telephone;
       this.courriel = courriel;
    }
   
    public String getClientid() {
        return this.clientid;
    }
    
    public void setClientid(String clientid) {
        this.clientid = clientid;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getCourriel() {
        return this.courriel;
    }
    
    public void setCourriel(String courriel) {
        this.courriel = courriel;
    }
    public Set getUtilisateurs() {
        return this.utilisateurs;
    }
    
    public void setUtilisateurs(Set utilisateurs) {
        this.utilisateurs = utilisateurs;
    }
    public Set getVisites() {
        return this.visites;
    }
    
    public void setVisites(Set visites) {
        this.visites = visites;
    }




}


