package Modele;
// Generated 2018-09-08 03:12:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clients generated by hbm2java
 */
public class Clients  implements java.io.Serializable {


     private String clientid;
     private String nom;
     private String prenom;
     private String telephone;
     private String courriel;
     private Set visiteses = new HashSet(0);

    public Clients() {
    }

	
    public Clients(String clientid, String nom) {
        this.clientid = clientid;
        this.nom = nom;
    }
    public Clients(String clientid, String nom, String prenom, String telephone, String courriel, Set visiteses) {
       this.clientid = clientid;
       this.nom = nom;
       this.prenom = prenom;
       this.telephone = telephone;
       this.courriel = courriel;
       this.visiteses = visiteses;
    }
   
    public String getClientid() {
        return this.clientid;
    }
    
    public void setClientid(String clientid) {
        this.clientid = clientid;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getCourriel() {
        return this.courriel;
    }
    
    public void setCourriel(String courriel) {
        this.courriel = courriel;
    }
    public Set getVisiteses() {
        return this.visiteses;
    }
    
    public void setVisiteses(Set visiteses) {
        this.visiteses = visiteses;
    }




}


