package Modele;
// Generated 2018-09-08 03:12:36 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Details generated by hbm2java
 */
public class Details  implements java.io.Serializable {


     private int numero;
     private String titre;
     private Integer nombrepieces;
     private Integer nombresdb;
     private Integer surface;
     private Date anneeconstruction;
     private String inclusion;
     private String exclusion;
     private String particularite;
     private String autresdescription;
     private Integer bienid;
     private String immeubleid;

    public Details() {
    }

	
    public Details(int numero) {
        this.numero = numero;
    }
    public Details(int numero, String titre, Integer nombrepieces, Integer nombresdb, Integer surface, Date anneeconstruction, String inclusion, String exclusion, String particularite, String autresdescription, Integer bienid, String immeubleid) {
       this.numero = numero;
       this.titre = titre;
       this.nombrepieces = nombrepieces;
       this.nombresdb = nombresdb;
       this.surface = surface;
       this.anneeconstruction = anneeconstruction;
       this.inclusion = inclusion;
       this.exclusion = exclusion;
       this.particularite = particularite;
       this.autresdescription = autresdescription;
       this.bienid = bienid;
       this.immeubleid = immeubleid;
    }
   
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    public Integer getNombrepieces() {
        return this.nombrepieces;
    }
    
    public void setNombrepieces(Integer nombrepieces) {
        this.nombrepieces = nombrepieces;
    }
    public Integer getNombresdb() {
        return this.nombresdb;
    }
    
    public void setNombresdb(Integer nombresdb) {
        this.nombresdb = nombresdb;
    }
    public Integer getSurface() {
        return this.surface;
    }
    
    public void setSurface(Integer surface) {
        this.surface = surface;
    }
    public Date getAnneeconstruction() {
        return this.anneeconstruction;
    }
    
    public void setAnneeconstruction(Date anneeconstruction) {
        this.anneeconstruction = anneeconstruction;
    }
    public String getInclusion() {
        return this.inclusion;
    }
    
    public void setInclusion(String inclusion) {
        this.inclusion = inclusion;
    }
    public String getExclusion() {
        return this.exclusion;
    }
    
    public void setExclusion(String exclusion) {
        this.exclusion = exclusion;
    }
    public String getParticularite() {
        return this.particularite;
    }
    
    public void setParticularite(String particularite) {
        this.particularite = particularite;
    }
    public String getAutresdescription() {
        return this.autresdescription;
    }
    
    public void setAutresdescription(String autresdescription) {
        this.autresdescription = autresdescription;
    }
    public Integer getBienid() {
        return this.bienid;
    }
    
    public void setBienid(Integer bienid) {
        this.bienid = bienid;
    }
    public String getImmeubleid() {
        return this.immeubleid;
    }
    
    public void setImmeubleid(String immeubleid) {
        this.immeubleid = immeubleid;
    }




}


