package Modele;
// Generated 2018-09-07 18:57:58 by Hibernate Tools 4.3.1



/**
 * EmployesId generated by hbm2java
 */
public class EmployesId  implements java.io.Serializable {


     private String employeid;
     private String nom;

    public EmployesId() {
    }

    public EmployesId(String employeid, String nom) {
       this.employeid = employeid;
       this.nom = nom;
    }
   
    public String getEmployeid() {
        return this.employeid;
    }
    
    public void setEmployeid(String employeid) {
        this.employeid = employeid;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmployesId) ) return false;
		 EmployesId castOther = ( EmployesId ) other; 
         
		 return ( (this.getEmployeid()==castOther.getEmployeid()) || ( this.getEmployeid()!=null && castOther.getEmployeid()!=null && this.getEmployeid().equals(castOther.getEmployeid()) ) )
 && ( (this.getNom()==castOther.getNom()) || ( this.getNom()!=null && castOther.getNom()!=null && this.getNom().equals(castOther.getNom()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmployeid() == null ? 0 : this.getEmployeid().hashCode() );
         result = 37 * result + ( getNom() == null ? 0 : this.getNom().hashCode() );
         return result;
   }   


}


