package Modele;
// Generated 2018-09-08 03:12:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Employes generated by hbm2java
 */
public class Employes  implements java.io.Serializable {


     private String employeid;
     private String nom;
     private String prenom;
     private String departement;
     private String fonction;
     private String nas;
     private Set visiteses = new HashSet(0);

    public Employes() {
    }

	
    public Employes(String employeid) {
        this.employeid = employeid;
    }
    public Employes(String employeid, String nom, String prenom, String departement, String fonction, String nas, Set visiteses) {
       this.employeid = employeid;
       this.nom = nom;
       this.prenom = prenom;
       this.departement = departement;
       this.fonction = fonction;
       this.nas = nas;
       this.visiteses = visiteses;
    }
   
    public String getEmployeid() {
        return this.employeid;
    }
    
    public void setEmployeid(String employeid) {
        this.employeid = employeid;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getDepartement() {
        return this.departement;
    }
    
    public void setDepartement(String departement) {
        this.departement = departement;
    }
    public String getFonction() {
        return this.fonction;
    }
    
    public void setFonction(String fonction) {
        this.fonction = fonction;
    }
    public String getNas() {
        return this.nas;
    }
    
    public void setNas(String nas) {
        this.nas = nas;
    }
    public Set getVisiteses() {
        return this.visiteses;
    }
    
    public void setVisiteses(Set visiteses) {
        this.visiteses = visiteses;
    }




}


