package Modele;
// Generated 2018-09-08 03:12:36 by Hibernate Tools 4.3.1



/**
 * ImagesId generated by hbm2java
 */
public class ImagesId  implements java.io.Serializable {


     private String immeubleid;
     private int bienid;
     private int imageid;

    public ImagesId() {
    }

    public ImagesId(String immeubleid, int bienid, int imageid) {
       this.immeubleid = immeubleid;
       this.bienid = bienid;
       this.imageid = imageid;
    }
   
    public String getImmeubleid() {
        return this.immeubleid;
    }
    
    public void setImmeubleid(String immeubleid) {
        this.immeubleid = immeubleid;
    }
    public int getBienid() {
        return this.bienid;
    }
    
    public void setBienid(int bienid) {
        this.bienid = bienid;
    }
    public int getImageid() {
        return this.imageid;
    }
    
    public void setImageid(int imageid) {
        this.imageid = imageid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ImagesId) ) return false;
		 ImagesId castOther = ( ImagesId ) other; 
         
		 return ( (this.getImmeubleid()==castOther.getImmeubleid()) || ( this.getImmeubleid()!=null && castOther.getImmeubleid()!=null && this.getImmeubleid().equals(castOther.getImmeubleid()) ) )
 && (this.getBienid()==castOther.getBienid())
 && (this.getImageid()==castOther.getImageid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getImmeubleid() == null ? 0 : this.getImmeubleid().hashCode() );
         result = 37 * result + this.getBienid();
         result = 37 * result + this.getImageid();
         return result;
   }   


}


