package Modele;
// Generated 2018-09-08 03:12:36 by Hibernate Tools 4.3.1



/**
 * Images generated by hbm2java
 */
public class Images  implements java.io.Serializable {


     private ImagesId id;
     private Immeuble immeuble;

    public Images() {
    }

    public Images(ImagesId id, Immeuble immeuble) {
       this.id = id;
       this.immeuble = immeuble;
    }
    
    public Images(ImagesId id) {
       this.id = id;
    }
   
    public ImagesId getId() {
        return this.id;
    }
    
    public void setId(ImagesId id) {
        this.id = id;
    }
    public Immeuble getImmeuble() {
        return this.immeuble;
    }
    
    public void setImmeuble(Immeuble immeuble) {
        this.immeuble = immeuble;
    }




}


