package Modele;
// Generated 2018-09-12 22:58:17 by Hibernate Tools 4.3.1



/**
 * Image generated by hbm2java
 */
public class Image  implements java.io.Serializable {


     private ImageId id;
     private Immeuble immeuble;
     private Bienimmobilier bienimmobilier;

    public Image() {
    }

    public Image(ImageId id, Immeuble immeuble, Bienimmobilier bienimmobilier) {
       this.id = id;
       this.immeuble = immeuble;
       this.bienimmobilier = bienimmobilier;
    }
     public Image(ImageId id) {
       this.id = id;
    }
    public ImageId getId() {
        return this.id;
    }
    
    public void setId(ImageId id) {
        this.id = id;
    }
    public Immeuble getImmeuble() {
        return this.immeuble;
    }
    
    public void setImmeuble(Immeuble immeuble) {
        this.immeuble = immeuble;
    }
    public Bienimmobilier getBienimmobilier() {
        return this.bienimmobilier;
    }
    
    public void setBienimmobilier(Bienimmobilier bienimmobilier) {
        this.bienimmobilier = bienimmobilier;
    }




}


