package Modele;
// Generated 2018-09-14 01:24:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import com.google.gson.annotations.SerializedName;
/**
 * Immeuble generated by hbm2java
 */
public class Immeuble  implements java.io.Serializable {


     private String immeubleid;
     private Adresse adresse;
     private String typeImmeuble;
     private Set bienimmobiliers = new HashSet(0);
     private Set images = new HashSet(0);

    public Immeuble() {
    }

	
    public Immeuble(String immeubleid) {
        this.immeubleid = immeubleid;
    }
    public Immeuble(String immeubleid, Adresse adresse, String typeImmeuble, Set bienimmobiliers, Set images) {
       this.immeubleid = immeubleid;
       this.adresse = adresse;
       this.typeImmeuble = typeImmeuble;
       this.bienimmobiliers = bienimmobiliers;
       this.images = images;
    }
    
    public Immeuble(String immeubleid, Adresse adresse, String typeImmeuble) {
       this.immeubleid = immeubleid;
       this.adresse = adresse;
       this.typeImmeuble = typeImmeuble;
    }
   
    public String getImmeubleid() {
        return this.immeubleid;
    }
    
    public void setImmeubleid(String immeubleid) {
        this.immeubleid = immeubleid;
    }
    public Adresse getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(Adresse adresse) {
        this.adresse = adresse;
    }
    public String getTypeImmeuble() {
        return this.typeImmeuble;
    }
    
    public void setTypeImmeuble(String typeImmeuble) {
        this.typeImmeuble = typeImmeuble;
    }
    public Set getBienimmobiliers() {
        return this.bienimmobiliers;
    }
    
    public void setBienimmobiliers(Set bienimmobiliers) {
        this.bienimmobiliers = bienimmobiliers;
    }
    public Set getImages() {
        return this.images;
    }
    
    public void setImages(Set images) {
        this.images = images;
    }

     public String toString (){
        return "Immeuble [adresse=" +this.adresse+", typeImmeuble=" +this.typeImmeuble+"]";
    }


}


