package Modele;
// Generated 2018-09-14 01:24:50 by Hibernate Tools 4.3.1



/**
 * UtilisateurId generated by hbm2java
 */
public class UtilisateurId  implements java.io.Serializable {


     private String nomutilisateur;
     private String courriel;

    public UtilisateurId() {
    }

    public UtilisateurId(String nomutilisateur, String courriel) {
       this.nomutilisateur = nomutilisateur;
       this.courriel = courriel;
    }
   
    public String getNomutilisateur() {
        return this.nomutilisateur;
    }
    
    public void setNomutilisateur(String nomutilisateur) {
        this.nomutilisateur = nomutilisateur;
    }
    public String getCourriel() {
        return this.courriel;
    }
    
    public void setCourriel(String courriel) {
        this.courriel = courriel;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UtilisateurId) ) return false;
		 UtilisateurId castOther = ( UtilisateurId ) other; 
         
		 return ( (this.getNomutilisateur()==castOther.getNomutilisateur()) || ( this.getNomutilisateur()!=null && castOther.getNomutilisateur()!=null && this.getNomutilisateur().equals(castOther.getNomutilisateur()) ) )
 && ( (this.getCourriel()==castOther.getCourriel()) || ( this.getCourriel()!=null && castOther.getCourriel()!=null && this.getCourriel().equals(castOther.getCourriel()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNomutilisateur() == null ? 0 : this.getNomutilisateur().hashCode() );
         result = 37 * result + ( getCourriel() == null ? 0 : this.getCourriel().hashCode() );
         return result;
   }   


}


