package Modele;
// Generated 2018-09-14 01:24:50 by Hibernate Tools 4.3.1



/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private UtilisateurId id;
     private Locataire locataire;
     private Client client;
     private Employe employe;
     private String motdepasse;
     private Integer photo;

    public Utilisateur() {
    }

	
    public Utilisateur(UtilisateurId id) {
        this.id = id;
    }
    public Utilisateur(UtilisateurId id, Locataire locataire, Client client, Employe employe, String motdepasse, Integer photo) {
       this.id = id;
       this.locataire = locataire;
       this.client = client;
       this.employe = employe;
       this.motdepasse = motdepasse;
       this.photo = photo;
    }
   public Utilisateur(UtilisateurId id, Locataire locataire, String motdepasse, Integer photo) {
       this.id = id;
       this.locataire = locataire;
       this.motdepasse = motdepasse;
       this.photo = photo;
    }
    public Utilisateur(UtilisateurId id,Client client, String motdepasse, Integer photo) {
       this.id = id;
       this.client = client;
       this.motdepasse = motdepasse;
       this.photo = photo;
    }
    public Utilisateur(UtilisateurId id,Employe employe, String motdepasse, Integer photo) {
       this.id = id;
       this.motdepasse = motdepasse;
       this.photo = photo;
    }
    public Utilisateur(UtilisateurId id,String motdepasse) {
       this.id = id;
       this.motdepasse = motdepasse;
    }
   
    public UtilisateurId getId() {
        return this.id;
    }
    
    public void setId(UtilisateurId id) {
        this.id = id;
    }
    public Locataire getLocataire() {
        return this.locataire;
    }
    
    public void setLocataire(Locataire locataire) {
        this.locataire = locataire;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }
    public String getMotdepasse() {
        return this.motdepasse;
    }
    
    public void setMotdepasse(String motdepasse) {
        this.motdepasse = motdepasse;
    }
    public Integer getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(Integer photo) {
        this.photo = photo;
    }




}


