package Modele;
// Generated 2018-09-08 03:12:36 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Visites generated by hbm2java
 */
public class Visites  implements java.io.Serializable {


     private VisitesId id;
     private Clients clients;
     private Employes employes;
     private Date heurefin;
     private Integer bienid;
     private String immeubleid;
     private String nom;

    public Visites() {
    }

	
    public Visites(VisitesId id) {
        this.id = id;
    }
    public Visites(VisitesId id, Clients clients, Employes employes, Date heurefin, Integer bienid, String immeubleid, String nom) {
       this.id = id;
       this.clients = clients;
       this.employes = employes;
       this.heurefin = heurefin;
       this.bienid = bienid;
       this.immeubleid = immeubleid;
       this.nom = nom;
    }
   
    public VisitesId getId() {
        return this.id;
    }
    
    public void setId(VisitesId id) {
        this.id = id;
    }
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }
    public Employes getEmployes() {
        return this.employes;
    }
    
    public void setEmployes(Employes employes) {
        this.employes = employes;
    }
    public Date getHeurefin() {
        return this.heurefin;
    }
    
    public void setHeurefin(Date heurefin) {
        this.heurefin = heurefin;
    }
    public Integer getBienid() {
        return this.bienid;
    }
    
    public void setBienid(Integer bienid) {
        this.bienid = bienid;
    }
    public String getImmeubleid() {
        return this.immeubleid;
    }
    
    public void setImmeubleid(String immeubleid) {
        this.immeubleid = immeubleid;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }




}


